# Dockerfile.dev
FROM python:3.11-slim

RUN apt-get update && apt-get install -y curl git build-essential && rm -rf /var/lib/apt/lists/*

# Install Poetry
ENV POETRY_HOME="/opt/poetry"
ENV PATH="$POETRY_HOME/bin:$PATH"
RUN curl -sSL https://install.python-poetry.org | python3 -

# Set up working directory and install dependencies
WORKDIR /app
COPY ./app/pyproject.toml ./app/poetry.lock* /app/
RUN poetry install --no-root

COPY ./app /app
RUN echo 'source /workspace/.devcontainer/.bashrc' >> /root/.bashrc
CMD [ "poetry", "run", "bash" ]
